################################################################################
# Test file for HTTP routes of userAdmin API
# REST Client for VSCode needed
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint = http://localhost:{{$dotenv PORT}}/api/admin/planning

### 404
GET {{ endpoint }}/azertyuiop

### Create employee affectation
POST {{ endpoint }}/assignment/user/
content-type: application/json

{
"starting_date": "2022-12-13",
"ending_date": "2022-12-13",
"color": "#0F0",
"position": 0,
"visibility": true,
"employee_id": 5,
"site_id": 5
}
