################################################################################
# Test file for HTTP routes of userAdmin API
# REST Client for VSCode needed
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint = http://localhost:{{$dotenv PORT}}/api/admin/company

### 404
GET {{ endpoint }}/azertyuiop

### Get all companies
GET {{ endpoint }}

### Get one company
GET {{ endpoint }}/1

### Get a company who does not exist
GET {{ endpoint }}/9999

### Get a company with an id as not a number
GET {{ endpoint }}/tartempion

### Create a company 
POST {{ endpoint }}
content-type: application/json

{
  "name": "JD - POST TEST Entreprise de test",
  "address": "JD - POST TEST Adresse de test",
  "zip_code": 34000,
  "type": "admin"
}

### Create an inexistant company
POST {{ endpoint }}
content-type: application/json

{
  "name": "JD - Entreprise de test",
  "address": "JD - Adresse de test",
  "zip_code": 34000,
  "type": "admin"
}

### Patch a company 
PATCH {{ endpoint }}/50
content-type: application/json

{
  "name": "JD - Entreprise de test",
  "address": "JD - Adresse de test",
  "zip_code": 34000,
  "type": "admin"
}

### Patch an inexistant company
PATCH {{ endpoint }}/999
content-type: application/json

{
  "name": "JD - Entreprise de test",
  "address": "JD - Adresse de test",
  "zip_code": 34000,
  "type": "admin"
}

### Delete a company
DELETE {{ endpoint }}/41

### Delete an inexistant company
DELETE {{ endpoint }}/999
